import { escapeHtml } from './escapeHtml'

export type PurchaseThankYouParams = {
  planName: string
  dashboardUrl: string
}

export function purchaseThankYouSubject(params: PurchaseThankYouParams): string {
  return `Welcome to FlowSight ${params.planName} 🎉`
}

export function purchaseThankYouHtml(params: PurchaseThankYouParams): string {
  const planName = escapeHtml(params.planName)
  const dashboardUrl = escapeHtml(params.dashboardUrl)

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>Welcome to FlowSight ${planName}</title></head>
<body style="font-family:'Plus Jakarta Sans',system-ui,sans-serif;background:#fafafa;margin:0;padding:24px;">
  <div style="max-width:560px;margin:0 auto;background:#fff;border:1px solid #e4e4e7;border-radius:12px;padding:32px;">
    <div style="margin-bottom:24px;">
      <p style="font-size:12px;color:#6366f1;margin:0 0 4px;text-transform:uppercase;letter-spacing:0.05em;font-weight:600;">FlowSight</p>
      <h1 style="font-size:22px;color:#18181b;margin:0;">You're officially on ${planName} 🎉</h1>
    </div>

    <p style="font-size:14px;color:#3f3f46;line-height:1.7;margin:0 0 16px;">
      Thank you for going Pro! Your payment was confirmed and your <strong>${planName}</strong> plan is active right now — no extra setup needed.
    </p>

    <p style="font-size:14px;color:#3f3f46;line-height:1.7;margin:0 0 24px;">
      You now have full access to deeper analytics, extended history, and the AI Coach. Jump back into your dashboard to keep going.
    </p>

    <div style="text-align:center;margin:0 0 28px;">
      <a href="${dashboardUrl}" style="display:inline-block;background:#6366f1;color:#ffffff;text-decoration:none;font-size:14px;font-weight:600;padding:12px 28px;border-radius:8px;">
        Open my dashboard
      </a>
    </div>

    <footer style="margin-top:8px;padding-top:16px;border-top:1px solid #e4e4e7;">
      <p style="font-size:12px;color:#a1a1aa;margin:0;">
        Generated by FlowSight · Privacy-first cognitive health analytics<br>
        Questions? Just reply to this email.
      </p>
    </footer>
  </div>
</body>
</html>`
}

export function purchaseThankYouText(params: PurchaseThankYouParams): string {
  const { planName, dashboardUrl } = params
  return [
    `You're officially on FlowSight ${planName}!`,
    '',
    `Thank you for going Pro. Your payment was confirmed and your ${planName} plan is active right now — no extra setup needed.`,
    '',
    `Open your dashboard: ${dashboardUrl}`,
    '',
    '— FlowSight · flowsight.site',
  ].join('\n')
}
