import { appUrl } from '@/lib/appUrl'
import type { WeeklyTeamReport } from '@/lib/buildWeeklyTeamReport'
import { escapeHtml } from './escapeHtml'

export function weeklyReportHtml(report: WeeklyTeamReport): string {
  const dashboardUrl = appUrl('/dashboard')
  const sectionsHtml = report.sections
    .map(
      (s) => `
      <section style="margin-bottom:24px;">
        <h2 style="font-size:16px;color:#18181b;margin:0 0 8px;">${escapeHtml(s.title)}</h2>
        <p style="font-size:14px;color:#3f3f46;line-height:1.6;margin:0;white-space:pre-wrap;">${escapeHtml(s.body)}</p>
      </section>`
    )
    .join('')

  const recsHtml =
    report.recommendations.length > 0
      ? `<ul style="margin:8px 0 0;padding-left:20px;color:#3f3f46;font-size:14px;line-height:1.8;">
          ${report.recommendations.map((r) => `<li>${escapeHtml(r)}</li>`).join('')}
        </ul>`
      : ''

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="color-scheme" content="light dark">
  <meta name="supported-color-schemes" content="light dark">
  <title>FlowSight Weekly Report</title>
</head>
<body style="font-family:'Plus Jakarta Sans',system-ui,sans-serif;background:#fafafa;margin:0;padding:24px;">
  <div style="max-width:640px;margin:0 auto;background:#fff;border:1px solid #e4e4e7;border-radius:12px;padding:32px;">
    <div style="margin-bottom:24px;">
      <p style="font-size:12px;color:#6366f1;margin:0 0 4px;text-transform:uppercase;letter-spacing:0.05em;font-weight:600;">FlowSight · Weekly Report</p>
      <h1 style="font-size:22px;color:#18181b;margin:0 0 4px;">${escapeHtml(report.teamName)}</h1>
      <p style="font-size:13px;color:#71717a;margin:0;">${escapeHtml(report.weekLabel)}</p>
    </div>

    <section style="margin-bottom:28px;padding:20px;background:#f4f4f5;border-radius:8px;">
      <h2 style="font-size:14px;color:#52525b;margin:0 0 10px;text-transform:uppercase;letter-spacing:0.04em;">Executive summary</h2>
      <p style="font-size:14px;color:#27272a;line-height:1.7;margin:0;white-space:pre-wrap;">${escapeHtml(report.executiveSummary)}</p>
      ${recsHtml}
    </section>

    ${sectionsHtml}

    <div style="text-align:center;margin:8px 0 4px;">
      <a href="${dashboardUrl}" style="display:inline-block;background:#6366f1;color:#ffffff;text-decoration:none;font-size:14px;font-weight:600;padding:12px 28px;border-radius:8px;">
        Open full dashboard
      </a>
    </div>

    <footer style="margin-top:24px;padding-top:16px;border-top:1px solid #e4e4e7;">
      <p style="font-size:12px;color:#a1a1aa;margin:0;">
        Generated by FlowSight · Privacy-first cognitive health analytics<br>
        Manage recipients and digest schedule from Settings → Notifications.
      </p>
    </footer>
  </div>
</body>
</html>`
}

export function weeklyReportPlainText(report: WeeklyTeamReport): string {
  const dashboardUrl = appUrl('/dashboard')
  const lines = [
    `FlowSight Weekly Report — ${report.teamName}`,
    report.weekLabel,
    '',
    'EXECUTIVE SUMMARY',
    report.executiveSummary,
    '',
  ]

  if (report.recommendations.length) {
    lines.push('RECOMMENDATIONS')
    report.recommendations.forEach((r) => lines.push(`• ${r}`))
    lines.push('')
  }

  for (const s of report.sections) {
    lines.push(s.title.toUpperCase())
    lines.push(s.body)
    lines.push('')
  }

  lines.push(`Open full dashboard: ${dashboardUrl}`)
  lines.push('Manage recipients and digest schedule from Settings → Notifications.')
  lines.push('')
  lines.push('— FlowSight · Privacy-first cognitive health analytics')
  return lines.join('\n')
}

export function weeklyReportSubject(report: WeeklyTeamReport): string {
  return `FlowSight weekly report — ${report.teamName} (${report.weekLabel})`
}
